# Generated by Django 5.2.7 on 2025-10-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_category_color_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='expenses', to='main_app.category'),
        ),
    ]
