# Generated by Django 5.2.7 on 2025-10-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_expense_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('last_four', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, related_name='expenses', to='main_app.paymentmethod'),
        ),
    ]
